# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-05-23 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_logo_url',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_name',
        ),
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
